[build]
  publish = "."

# Custom domain settings
[context.production]
  environment = { NETLIFY_SITE_NAME = "yvonnesprivatehomecare.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
